DROP TABLE IF EXISTS "bet_selections";
DROP TABLE IF EXISTS "results";
DROP TABLE IF EXISTS "odds";
DROP TABLE IF EXISTS "markets";
DROP TABLE IF EXISTS "events";
DROP TABLE IF EXISTS "sports";
DROP TABLE IF EXISTS "company_finances";
DROP TABLE IF EXISTS "transactions";
DROP TABLE IF EXISTS "user_roles";
DROP TABLE IF EXISTS "bets";
DROP TABLE IF EXISTS "users";

DROP TYPE IF EXISTS "bet_status_enum";
DROP TYPE IF EXISTS "event_status_enum";
DROP TYPE IF EXISTS "transaction_type_enum";


CREATE TYPE "transaction_type_enum" AS ENUM (
  'DEPOSIT',
  'WITHDRAWAL',
  'BET_PLACEMENT',
  'BET_WINNING',
  'BET_REFUND'
);

CREATE TYPE "event_status_enum" AS ENUM (
  'UPCOMING',
  'LIVE',
  'FINISHED',
  'CANCELLED'
);

CREATE TYPE "bet_status_enum" AS ENUM (
  'PENDING',
  'WON',
  'LOST',
  'VOID'
);


CREATE TABLE "users" (
                         "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" VARCHAR(50) UNIQUE NOT NULL,
                         "first_name" VARCHAR(50) NOT NULL,
                         "last_name" VARCHAR(50) NOT NULL,
                         "personal_id_number" VARCHAR(50) UNIQUE NOT NULL,
                         "password_hash" VARCHAR(255) NOT NULL,
                         "email" VARCHAR(100) UNIQUE NOT NULL,
                         "cash_balance" DECIMAL(15,2) NOT NULL DEFAULT 0,
                         "bonus_balance" DECIMAL(15,2) NOT NULL DEFAULT 0,
                         "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "user_roles" (
                              "user_id" BIGINT,
                              "role_id" INT,
                              "role_name" VARCHAR(50) UNIQUE NOT NULL,
                              PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "bets" (
                        "bet_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "user_id" BIGINT NOT NULL,
                        "stake" DECIMAL(15,2) NOT NULL,
                        "total_odd" DECIMAL(10,4) NOT NULL,
                        "potential_payout" DECIMAL(15,2) NOT NULL,
                        "bet_status" bet_status_enum NOT NULL DEFAULT 'PENDING',
                        "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "transactions" (
                                "transaction_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "user_id" BIGINT NOT NULL,
                                "transaction_type" transaction_type_enum NOT NULL,
                                "amount" DECIMAL(15,2) NOT NULL,
                                "related_bet_id" BIGINT,
                                "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "company_finances" (
                                    "id" INT PRIMARY KEY DEFAULT 1,
                                    "total_balance" DECIMAL(20,2) NOT NULL,
                                    "last_calculated_at" TIMESTAMP NOT NULL
);

CREATE TABLE "sports" (
                          "sport_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "sport_name" VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE "events" (
                          "event_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "sport_id" INT NOT NULL,
                          "event_name" VARCHAR(255) NOT NULL,
                          "start_time" TIMESTAMP NOT NULL,
                          "event_status" event_status_enum NOT NULL
);

CREATE TABLE "markets" (
                           "market_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "event_id" BIGINT NOT NULL,
                           "market_name" VARCHAR(100) NOT NULL,
                           "is_settled" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "odds" (
                        "odd_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "market_id" BIGINT NOT NULL,
                        "outcome_name" VARCHAR(100) NOT NULL,
                        "odd_value" DECIMAL(10,4) NOT NULL,
                        "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "results" (
                           "result_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "market_id" BIGINT UNIQUE NOT NULL,
                           "winning_odd_id" BIGINT NOT NULL,
                           "settled_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "bet_selections" (
                                  "selection_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "bet_id" BIGINT NOT NULL,
                                  "market_id" BIGINT NOT NULL,
                                  "odd_id" BIGINT NOT NULL,
                                  "odd_value_at_bet_time" DECIMAL(10,4) NOT NULL,
                                  "selection_status" bet_status_enum NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_personal_id_number ON users(personal_id_number);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);

CREATE INDEX idx_bets_user_id ON bets(user_id);
CREATE INDEX idx_bets_created_at ON bets(created_at);

CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_created_at ON transactions(created_at);
CREATE INDEX idx_transactions_related_bet_id ON transactions(related_bet_id);

CREATE INDEX idx_events_sport_id ON events(sport_id);
CREATE INDEX idx_events_start_time ON events(start_time);

CREATE INDEX idx_markets_event_id ON markets(event_id);
CREATE INDEX idx_markets_is_settled ON markets(is_settled);

CREATE INDEX idx_odds_market_id ON odds(market_id);
CREATE INDEX idx_odds_is_active ON odds(is_active);
CREATE INDEX idx_odds_market_active ON odds(market_id, is_active);

CREATE INDEX idx_results_market_id ON results(market_id);

CREATE INDEX idx_bet_selections_bet_id ON bet_selections(bet_id);
CREATE INDEX idx_bet_selections_market_id ON bet_selections(market_id);
CREATE INDEX idx_bet_selections_odd_id ON bet_selections(odd_id);
CREATE INDEX idx_bet_selections_bet_market ON bet_selections(bet_id, market_id);


ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
ALTER TABLE "events" ADD FOREIGN KEY ("sport_id") REFERENCES "sports" ("sport_id");
ALTER TABLE "markets" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("event_id");
ALTER TABLE "odds" ADD FOREIGN KEY ("market_id") REFERENCES "markets" ("market_id");
ALTER TABLE "results" ADD FOREIGN KEY ("market_id") REFERENCES "markets" ("market_id");
ALTER TABLE "results" ADD FOREIGN KEY ("winning_odd_id") REFERENCES "odds" ("odd_id");
ALTER TABLE "bets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
ALTER TABLE "bet_selections" ADD FOREIGN KEY ("bet_id") REFERENCES "bets" ("bet_id");
ALTER TABLE "bet_selections" ADD FOREIGN KEY ("market_id") REFERENCES "markets" ("market_id");
ALTER TABLE "bet_selections" ADD FOREIGN KEY ("odd_id") REFERENCES "odds" ("odd_id");